- name: Create stack user
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    create_home: true

- name: Allow stack user to have passwordless sudo
  lineinfile:
    path: /etc/sudoers.d/stack
    line: 'stack ALL=(ALL) NOPASSWD: ALL'
    create: yes
    mode: 0440

- name: Ensure home directory is executable
  file:
    path: /opt/stack
    mode: '0755'