---
- name: Create stack user
  ansible.builtin.user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    create_home: true
    state: present
  become: yes

- name: Allow stack user to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/stack
    line: "stack ALL=(ALL) NOPASSWD: ALL"
    create: yes
    mode: "0440"
    state: present
    validate: "visudo -cf %s"
  become: yes

- name: Ensure home directory is executable
  ansible.builtin.file:
    path: /opt/stack
    mode: "0755"
    state: directory
  become: yes